{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acquireio",
    "module": "core",
    "version": "2.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.emoji",
          "module": "emoji-appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "pl.droidsonroids.gif",
          "module": "android-gif-drawable",
          "version": {
            "requires": "1.2.20"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        },
        {
          "group": "com.github.amitshekhariitbhu.Fast-Android-Networking",
          "module": "android-networking",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-2.4.3.aar",
          "url": "core-2.4.3.aar",
          "size": 19154302,
          "sha512": "7133829cbf987d284a70cfde51d80de94fb74cc307af096f0e251b3f2f37211c4e3ff211b0a668f96d92747e80dbb9a4338ff018d4fa4f9d2bf8eeeeafeed78a",
          "sha256": "915721e0b58bf9c4376e3bcf0b3656bd961be9ed5b729f7ffec7dc1f29a8059e",
          "sha1": "2c5c578b5e127c23f64a7a7e38644b6ba21829bd",
          "md5": "1a2199f0993b537d12b86d2d7361b39f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.emoji",
          "module": "emoji-appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "pl.droidsonroids.gif",
          "module": "android-gif-drawable",
          "version": {
            "requires": "1.2.20"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        },
        {
          "group": "com.github.amitshekhariitbhu.Fast-Android-Networking",
          "module": "android-networking",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-2.4.3.aar",
          "url": "core-2.4.3.aar",
          "size": 19154302,
          "sha512": "7133829cbf987d284a70cfde51d80de94fb74cc307af096f0e251b3f2f37211c4e3ff211b0a668f96d92747e80dbb9a4338ff018d4fa4f9d2bf8eeeeafeed78a",
          "sha256": "915721e0b58bf9c4376e3bcf0b3656bd961be9ed5b729f7ffec7dc1f29a8059e",
          "sha1": "2c5c578b5e127c23f64a7a7e38644b6ba21829bd",
          "md5": "1a2199f0993b537d12b86d2d7361b39f"
        }
      ]
    }
  ]
}
